USE DATABASE COLLEGE_TRANSPORT;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS STUDENTS (
    STUDENT_ID VARCHAR(20),
    NAME VARCHAR(100),
    DEPARTMENT VARCHAR(20),
    YEAR NUMBER(1,0),
    BUS_ID VARCHAR(20),
    STOP_ID VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS BUSES (
    BUS_ID VARCHAR(20),
    ROUTE VARCHAR(50),
    TOTAL_CAPACITY NUMBER(5,0),
    DRIVER VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS STOPS (
    STOP_ID VARCHAR(20),
    STOP_NAME VARCHAR(100),
    AREA VARCHAR(100),
    DISTANCE_KM NUMBER(6,2)
);

CREATE TABLE IF NOT EXISTS BUS_USAGE (
    DATE DATE,
    BUS_ID VARCHAR(20),
    STUDENTS_BOARDED NUMBER(5,0),
    ARRIVAL_TIME TIME,
    DEPARTURE_TIME TIME,
    DELAY_MINUTES NUMBER(5,0)
);

CREATE TABLE IF NOT EXISTS COMPLAINTS (
    COMPLAINT_ID VARCHAR(20),
    DATE DATE,
    BUS_ID VARCHAR(20),
    STUDENT_ID VARCHAR(20),
    CATEGORY VARCHAR(50),
    DESCRIPTION VARCHAR(500)
);
