USE DATABASE COLLEGE_TRANSPORT;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW BUS_UTILIZATION AS
WITH daily_util AS (
    SELECT 
        u.DATE,
        u.BUS_ID,
        b.ROUTE,
        u.STUDENTS_BOARDED,
        b.TOTAL_CAPACITY,
        (u.STUDENTS_BOARDED * 100.0 / NULLIF(b.TOTAL_CAPACITY, 0)) AS UTILIZATION_PERCENT
    FROM RAW.BUS_USAGE u
    JOIN RAW.BUSES b ON u.BUS_ID = b.BUS_ID
)
SELECT 
    DATE,
    BUS_ID,
    ROUTE,
    STUDENTS_BOARDED,
    TOTAL_CAPACITY,
    UTILIZATION_PERCENT,
    CASE 
        WHEN UTILIZATION_PERCENT < 40 THEN 'Underutilized'
        WHEN UTILIZATION_PERCENT >= 40 AND UTILIZATION_PERCENT < 70 THEN 'Normal'
        WHEN UTILIZATION_PERCENT >= 70 AND UTILIZATION_PERCENT < 85 THEN 'High'
        WHEN UTILIZATION_PERCENT >= 85 AND UTILIZATION_PERCENT <= 100 THEN 'Critical'
        WHEN UTILIZATION_PERCENT > 100 THEN 'Over-capacity'
        ELSE 'Unknown'
    END AS UTILIZATION_CATEGORY
FROM daily_util;

CREATE OR REPLACE VIEW BUS_UTILIZATION_SUMMARY AS
SELECT 
    BUS_ID,
    ROUTE,
    TOTAL_CAPACITY,
    AVG(STUDENTS_BOARDED) AS AVG_STUDENTS_BOARDED,
    AVG(UTILIZATION_PERCENT) AS AVG_UTILIZATION_PERCENT,
    MAX(UTILIZATION_PERCENT) AS MAX_UTILIZATION_PERCENT
FROM BUS_UTILIZATION
GROUP BY BUS_ID, ROUTE, TOTAL_CAPACITY;
