USE DATABASE COLLEGE_TRANSPORT;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW DELAY_ANALYSIS AS
SELECT 
    u.DATE,
    u.BUS_ID,
    b.ROUTE,
    u.DELAY_MINUTES,
    CASE
        WHEN u.DELAY_MINUTES = 0 THEN 'On Time'
        WHEN u.DELAY_MINUTES > 0 AND u.DELAY_MINUTES <= 5 THEN 'Minor Delay'
        WHEN u.DELAY_MINUTES > 5 AND u.DELAY_MINUTES <= 15 THEN 'Moderate Delay'
        WHEN u.DELAY_MINUTES > 15 THEN 'Severe Delay'
        ELSE 'Unknown'
    END AS DELAY_SEVERITY
FROM RAW.BUS_USAGE u
JOIN RAW.BUSES b ON u.BUS_ID = b.BUS_ID;

CREATE OR REPLACE VIEW DELAY_SUMMARY AS
SELECT 
    BUS_ID,
    ROUTE,
    COUNT(DATE) AS TOTAL_TRIPS,
    SUM(IFF(DELAY_MINUTES > 0, 1, 0)) AS DELAYED_TRIPS,
    (SUM(IFF(DELAY_MINUTES > 0, 1, 0)) * 100.0 / NULLIF(COUNT(DATE), 0)) AS DELAY_RATE_PERCENT,
    AVG(DELAY_MINUTES) AS AVG_DELAY_MINUTES,
    MAX(DELAY_MINUTES) AS MAX_DELAY_MINUTES
FROM DELAY_ANALYSIS
GROUP BY BUS_ID, ROUTE;
