USE DATABASE COLLEGE_TRANSPORT;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW ROUTE_PERFORMANCE AS
WITH usage_stats AS (
    SELECT 
        b.ROUTE,
        COUNT(u.DATE) AS TOTAL_TRIPS,
        AVG(u.STUDENTS_BOARDED) AS AVG_PASSENGERS,
        AVG(u.STUDENTS_BOARDED * 100.0 / NULLIF(b.TOTAL_CAPACITY, 0)) AS AVG_UTILIZATION,
        AVG(u.DELAY_MINUTES) AS AVG_DELAY
    FROM RAW.BUS_USAGE u
    JOIN RAW.BUSES b ON u.BUS_ID = b.BUS_ID
    GROUP BY b.ROUTE
),
complaint_stats AS (
    SELECT 
        b.ROUTE,
        COUNT(c.COMPLAINT_ID) AS COMPLAINT_COUNT
    FROM RAW.COMPLAINTS c
    JOIN RAW.BUSES b ON c.BUS_ID = b.BUS_ID
    GROUP BY b.ROUTE
)
SELECT 
    u.ROUTE,
    u.TOTAL_TRIPS,
    u.AVG_PASSENGERS,
    u.AVG_UTILIZATION,
    u.AVG_DELAY,
    COALESCE(c.COMPLAINT_COUNT, 0) AS COMPLAINT_COUNT,
    GREATEST(0, 100 - (u.AVG_DELAY * 2) - (COALESCE(c.COMPLAINT_COUNT, 0) * 1.5) - ABS(u.AVG_UTILIZATION - 70)) AS HEALTH_SCORE,
    RANK() OVER(ORDER BY 
        (100 - (u.AVG_DELAY * 2) - (COALESCE(c.COMPLAINT_COUNT, 0) * 1.5) - ABS(u.AVG_UTILIZATION - 70)) DESC
    ) AS ROUTE_RANKING
FROM usage_stats u
LEFT JOIN complaint_stats c ON u.ROUTE = c.ROUTE;
