USE DATABASE COLLEGE_TRANSPORT;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW COMPLAINT_CATEGORY_DISTRIBUTION AS
SELECT 
    CATEGORY,
    COUNT(*) AS COMPLAINT_COUNT,
    (COUNT(*) * 100.0 / SUM(COUNT(*)) OVER()) AS PERCENTAGE
FROM RAW.COMPLAINTS
GROUP BY CATEGORY;

CREATE OR REPLACE VIEW COMPLAINTS_PER_BUS AS
SELECT 
    c.BUS_ID,
    b.ROUTE,
    COUNT(c.COMPLAINT_ID) AS TOTAL_COMPLAINTS
FROM RAW.COMPLAINTS c
JOIN RAW.BUSES b ON c.BUS_ID = b.BUS_ID
GROUP BY c.BUS_ID, b.ROUTE;

CREATE OR REPLACE VIEW COMPLAINT_TRENDS AS
SELECT 
    DATE,
    COUNT(COMPLAINT_ID) AS COMPLAINT_COUNT
FROM RAW.COMPLAINTS
GROUP BY DATE;

CREATE OR REPLACE VIEW TOP_COMPLAINTS_PER_BUS AS
WITH ranked_complaints AS (
    SELECT 
        BUS_ID,
        CATEGORY,
        COUNT(COMPLAINT_ID) AS COMPLAINT_COUNT,
        ROW_NUMBER() OVER(PARTITION BY BUS_ID ORDER BY COUNT(COMPLAINT_ID) DESC) as rn
    FROM RAW.COMPLAINTS
    GROUP BY BUS_ID, CATEGORY
)
SELECT BUS_ID, CATEGORY, COMPLAINT_COUNT
FROM ranked_complaints
WHERE rn = 1;
