USE DATABASE COLLEGE_TRANSPORT;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW DEPT_TRANSPORT_USERS AS
SELECT 
    DEPARTMENT,
    COUNT(STUDENT_ID) AS USERS_COUNT
FROM RAW.STUDENTS
GROUP BY DEPARTMENT;

CREATE OR REPLACE VIEW YEAR_TRANSPORT_USERS AS
SELECT 
    YEAR,
    COUNT(STUDENT_ID) AS USERS_COUNT
FROM RAW.STUDENTS
GROUP BY YEAR;

CREATE OR REPLACE VIEW STUDENTS_PER_BUS AS
SELECT 
    s.BUS_ID,
    b.ROUTE,
    COUNT(s.STUDENT_ID) AS ALLOCATED_STUDENTS
FROM RAW.STUDENTS s
JOIN RAW.BUSES b ON s.BUS_ID = b.BUS_ID
GROUP BY s.BUS_ID, b.ROUTE;
