USE DATABASE COLLEGE_TRANSPORT;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW STUDENTS_PER_STOP AS
SELECT 
    s.STOP_ID,
    st.STOP_NAME,
    COUNT(s.STUDENT_ID) AS STUDENT_COUNT
FROM RAW.STUDENTS s
JOIN RAW.STOPS st ON s.STOP_ID = st.STOP_ID
GROUP BY s.STOP_ID, st.STOP_NAME;

CREATE OR REPLACE VIEW STOP_DISTANCE_ANALYSIS AS
SELECT 
    STOP_ID,
    STOP_NAME,
    AREA,
    DISTANCE_KM
FROM RAW.STOPS;

CREATE OR REPLACE VIEW STOP_RANKING AS
SELECT 
    s.STOP_ID,
    st.STOP_NAME,
    COUNT(s.STUDENT_ID) AS USAGE_COUNT,
    RANK() OVER(ORDER BY COUNT(s.STUDENT_ID) DESC) AS USAGE_RANK
FROM RAW.STUDENTS s
JOIN RAW.STOPS st ON s.STOP_ID = st.STOP_ID
GROUP BY s.STOP_ID, st.STOP_NAME;
