USE DATABASE COLLEGE_TRANSPORT;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW TRANSPORT_KPIS AS
SELECT 
    (SELECT COUNT(*) FROM RAW.STUDENTS) AS TOTAL_STUDENTS,
    (SELECT COUNT(*) FROM RAW.BUSES) AS TOTAL_BUSES,
    (SELECT COUNT(DISTINCT ROUTE) FROM RAW.BUSES) AS TOTAL_ROUTES,
    (SELECT COUNT(*) FROM RAW.STOPS) AS TOTAL_STOPS,
    (SELECT COUNT(*) FROM RAW.BUS_USAGE) AS TOTAL_TRIPS,
    
    (SELECT AVG(STUDENTS_BOARDED * 100.0 / NULLIF(b.TOTAL_CAPACITY, 0)) FROM RAW.BUS_USAGE u JOIN RAW.BUSES b ON u.BUS_ID = b.BUS_ID) AS AVG_UTILIZATION,
    (SELECT MAX(STUDENTS_BOARDED * 100.0 / NULLIF(b.TOTAL_CAPACITY, 0)) FROM RAW.BUS_USAGE u JOIN RAW.BUSES b ON u.BUS_ID = b.BUS_ID) AS MAX_UTILIZATION,
    (SELECT MIN(STUDENTS_BOARDED * 100.0 / NULLIF(b.TOTAL_CAPACITY, 0)) FROM RAW.BUS_USAGE u JOIN RAW.BUSES b ON u.BUS_ID = b.BUS_ID) AS MIN_UTILIZATION,
    
    (SELECT COUNT(DISTINCT u.BUS_ID) FROM RAW.BUS_USAGE u JOIN RAW.BUSES b ON u.BUS_ID = b.BUS_ID WHERE (u.STUDENTS_BOARDED * 100.0 / NULLIF(b.TOTAL_CAPACITY, 0)) > 100) AS OVERCROWDED_BUSES,
    (SELECT COUNT(DISTINCT u.BUS_ID) FROM RAW.BUS_USAGE u JOIN RAW.BUSES b ON u.BUS_ID = b.BUS_ID WHERE (u.STUDENTS_BOARDED * 100.0 / NULLIF(b.TOTAL_CAPACITY, 0)) < 40) AS UNDERUTILIZED_BUSES,
    
    (SELECT COUNT(*) FROM RAW.BUS_USAGE WHERE DELAY_MINUTES > 0) AS TOTAL_DELAYED_TRIPS,
    (SELECT AVG(DELAY_MINUTES) FROM RAW.BUS_USAGE) AS AVG_DELAY,
    (SELECT MAX(DELAY_MINUTES) FROM RAW.BUS_USAGE) AS MAX_DELAY,
    
    (SELECT COUNT(*) FROM RAW.COMPLAINTS) AS TOTAL_COMPLAINTS,
    
    CASE 
        WHEN (SELECT AVG(DELAY_MINUTES) FROM RAW.BUS_USAGE) > 10 THEN 'Critical'
        WHEN (SELECT COUNT(*) FROM RAW.COMPLAINTS) > 100 THEN 'Warning'
        ELSE 'Healthy'
    END AS SYSTEM_HEALTH_STATUS;
