USE DATABASE COLLEGE_TRANSPORT;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW BUS_RISK_SCORE AS
WITH metrics AS (
    SELECT 
        b.BUS_ID,
        b.ROUTE,
        AVG(u.STUDENTS_BOARDED * 100.0 / NULLIF(b.TOTAL_CAPACITY, 0)) AS avg_util,
        AVG(u.DELAY_MINUTES) AS avg_delay,
        COUNT(DISTINCT c.COMPLAINT_ID) AS complaint_count
    FROM RAW.BUSES b
    LEFT JOIN RAW.BUS_USAGE u ON b.BUS_ID = u.BUS_ID
    LEFT JOIN RAW.COMPLAINTS c ON b.BUS_ID = c.BUS_ID
    GROUP BY b.BUS_ID, b.ROUTE
)
SELECT 
    BUS_ID,
    ROUTE,
    avg_util,
    avg_delay,
    complaint_count,
    GREATEST(0, avg_util - 85) * 2 AS utilization_risk,
    avg_delay * 1.5 AS delay_risk,
    complaint_count * 2.0 AS complaint_risk,
    (GREATEST(0, avg_util - 85) * 2) + (avg_delay * 1.5) + (complaint_count * 2.0) AS COMPOSITE_RISK_SCORE
FROM metrics;

CREATE OR REPLACE VIEW ROUTE_HEALTH AS
SELECT * FROM ROUTE_PERFORMANCE;

CREATE OR REPLACE VIEW TRANSPORT_SUMMARY AS
SELECT * FROM TRANSPORT_KPIS;

CREATE OR REPLACE VIEW AI_BUS_DETAIL AS
SELECT 
    r.BUS_ID,
    r.ROUTE,
    r.COMPOSITE_RISK_SCORE,
    u.AVG_UTILIZATION_PERCENT,
    d.DELAY_RATE_PERCENT,
    d.AVG_DELAY_MINUTES,
    c.TOTAL_COMPLAINTS
FROM BUS_RISK_SCORE r
LEFT JOIN BUS_UTILIZATION_SUMMARY u ON r.BUS_ID = u.BUS_ID
LEFT JOIN DELAY_SUMMARY d ON r.BUS_ID = d.BUS_ID
LEFT JOIN COMPLAINTS_PER_BUS c ON r.BUS_ID = c.BUS_ID;
